GridLayout:
    cols: 3
    rows: None

    row_default_height:50
    row_force_default: True

#    col_default_width: 50
#    col_force_default: True
    Button:
        size_hint: .1, None
        text: "A"
    Button:
        text: "B"
    Button:
        text: "C"
    Button:
        size_hint: .1, None
        text: "D"

    Button:
        text: "E"
    Button:

        text: "F"
    Button:
        size_hint: .1, None
        text: "G"
    Button:
        text: "H"
