

StackLayout
    orientation: "bt-rl"
    padding: 20 # deistancia ate a margem
    spacing: 40 # distancia entre os componentes
    Label
        text: "tudo de boas"
        font_size: 20
    Label
        text: "tudo trankis"
        font_name: "consola"
    Label
        text: "tudo suave"
        bold: True
    Label
        text: "tudo tranquilo"
        italic: True
        font_size: 20
        color: .1,.2,.3,1
        disabled: True